name: 'CI'

on:
  push:

jobs:
  run-checks:
    name: Format, lint, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check

      - name: Check linting
        run: pnpm lint:check

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build
